#!/bin/bash --

set -o pipefail

function _error
{
    echo "#####"
    echo "ERROR: $1" 1>&2
    echo "#####"
    exit $2
}

function _warn
{
    echo "#####"
    echo "WARN: $1" 1>&2
    echo "#####"
}

function _info
{
    echo "#####"
    echo "INFO: $1"
    echo "#####"
    sleep 1
}

###
# Step 0: clone ADTOOLS for use with afxgroup CLIB2, build for 11.3 GCC and 2.23.2 binutils
###
which ppc-amigaos-gcc  && _error "ERROR: Remove older ADTOOLS install from your path" 10 ;

BASE_DIR="$(pwd)/build"
ORIG_DIR="$(pwd)"
if (( $# >= 1 ))
then
    _info "All other arguments will be passed to tests/Makefile"
fi

if [[ ! -d "$BASE_DIR" ]]
then
   mkdir "$BASE_DIR"
   cd "$BASE_DIR"
   mkdir 4afx
   cd 4afx
   git clone https://github.com/sba1/adtools.git 4afx_adtools
   cd 4afx_adtools

   git submodule init
   git submodule update
   gild/bin/gild checkout binutils 2.23.2
   gild/bin/gild checkout gcc 11

   # We shall use the rs6k amigaos.h version from the afxgroup CLIB2
   sed -i '115i\	cp downloads/clib2/misc/amigaos.h ../gcc/repo/gcc/config/rs6000/' native-build/makefile
   # And, we need to remove -Werror when building clib2 due to time cast issue
   sed -i '115i\	sed -i "s|-Werror|# -Werror|g" downloads/clib2/GNUmakefile.os4' native-build/makefile
   # We also want to build SHARED LIBRARIES for CLIB2
   sed -i 's|SHARED=no|SHARED=yes|' native-build/makefile

   CORES=$(nproc)
   if [[ -z ${CORES} ]] ; then CORES=1 ; fi
   
   CROSS_PREFIX="$BASE_DIR"/4afx/4afx_build EXP_CLIB2=1  make -j${CORES} -C native-build/ gcc-cross  2>&1 | tee "$BASE_DIR"/4afx/4afx.log \
       || _error "The compilation failed. See the log file: \"$BASE_DIR\"/4afx/4afx.log" 40
else
    _warn "\"$BASE_DIR\" already exists, assuming that you just want to re-run the tests"
fi

cd "$ORIG_DIR"
###
# Step 1: Run some test programs
###
export PATH="$BASE_DIR"/4afx/4afx_build/bin:"$PATH"
# Arbitrary check
which ppc-amigaos-gcc 1>/dev/null 2>&1 || _error "Expected to find the cross GCC compiler on the path" 30

_info "Running tests in $(pwd)/tests. See log (log*.txt) files for details"

cd tests
make clean
make NO_DYN=1 "$@" all
make all "$@"
cd ..

exit 0
