#!/bin/bash --
# Insert any modifications to ADTOOLS before building it here:
set -e
set -u

# WHEN THIS SCRIPT IS INVOKED YOU ARE ALREADY INSIDE THE CHECKED OUT LOCATION OF ADTOOLS
#
# So, for example you can invoke:
#
#     cp /home/user/Downloads/makefile native-build/
#
# to replace the makefile in the checked out ADTOOLS location for this session
#
# Or, you may want some small in-place hacks:
# 
# if (( EXP_CLIB2 ))
# then
#     # We shall use the rs6k amigaos.h version from the afxgroup CLIB2
#     sed -i '115i\	cp downloads/clib2/misc/amigaos.h ../gcc/repo/gcc/config/rs6000/' native-build/makefile
#     # And, we need to remove -Werror when building clib2 due to time cast issue
#     sed -i '115i\	sed -i "s|-Werror|# -Werror|g" downloads/clib2/GNUmakefile.os4' native-build/makefile
#     # We also want to build SHARED LIBRARIES for CLIB2
#     sed -i 's|SHARED=no|SHARED=yes|' native-build/makefile
# fi
